### ISSUE TITLE
Product Page Template Save JSON Errror 500

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1248]
**Describe the bug**
Cannot save product page template most of the time due to json error 500

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Expected behavior**
*Product page template should save*

**What actually happens**
error 500
Seems to be related to beginning part of the saving of the data:

```
<form class="variations_form cart" action="https://staging.workcycles.com/product/workcycles-kr8/" method="post" enctype='multipart/form-data' data-product_id="5121" data-product_variations="[{&quot;attributes&quot;:{&quot;attribute_pa_color_kr8&quot;:&quot;black-dice&quot;,&quot;attribute_pa_gears_and_brakes&quot;:&quot;nn8d-hand-brakes-8-speed&quot;},&quot;availability_html&quot;:&quot;&quot;,&quot;backorders_allowed&quot;:false,&quot;dimensions&quot;:{&quot;length&quot;:&quot;&quot;,&quot;width&quot;:&quot;&quot;,&quot;height&quot;:&quot;&quot;},&quot;dimensions_html&quot;:&quot;N\/A&quot;,&quot;display_price&quot;:2023.970000000000027284841053187847137451171875,&quot;display_regular_price&
```
**Screenshots**

![Screen Shot 2020-06-11 at 4 54 04 PM](https://user-images.githubusercontent.com/344138/84371652-2e9b5580-ac04-11ea-8ac8-24326e6ab52c.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina
 - Browser Firefox Developer
 - Oxygen Version 3.2

**Comment by jasperf** [comment]
Does seem to be related to global add-ons by [WooCommerce Product Add-Ons Ultimate](https://pluginrepublic.com/wordpress-plugins/woocommerce-product-add-ons-ultimate/). This because when the product in question is not connected to the new global group the page loads just fine. Will open an issue there as well.

**Comment by jasperf** [comment]
checked debug log and found a fatal error:

```
[12-Jun-2020 01:41:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_sku() on bool in /home/debxxxxxx/domains/domain.com/public_html/staging/wp-content/plugins/product-extras-for-woocommerce/templates/frontend/products/products-swatches.php:52
Stack trace:
#0 /home/debxxxxxxx/domains/domain.com/public_html/staging/wp-content/plugins/product-extras-for-woocommerce/templates/frontend/products.php(28): include()

#1 /home/debxxxxxxx/domains/domain.com/public_html/staging/wp-content/plugins/product-extras-for-woocommerce/inc/functions-single-product.php(425): include('/home/deb102138...')

#2 /home/debxxxxxx/domains/domain.com/public_html/staging/wp-includes/class-wp-hook.php(287): pewc_product_extra_fields('')

#3 /home/debxxxxxx/domains/domain.com/public_html/staging/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)

#4 /home/debxxxxxx/domains/domain.com/public_html/staging/wp-includes/plugin.php(478): WP_Hook->do_action(Array)

#5 /home/debxxxxxxx/domains/domain.com/public_html/s in /home/deb102138n3/domains/domain.com/public_html/staging/wp-content/plugins/product-extras-for-woocommerce/templates/frontend/products/products-swatches.php on line 52
```

related to Product Extras for WooCommerce  wp-content/plugins/product-extras-for-woocommerce/templates/frontend/products/products-swatches.php

`$main_sku = $default_variation->get_sku();`

which is WooCommerce Product Add-Ons Ultimate. And this occurred with the latest version as well as far as I can see.

Not sure if this causes the template saving issue nor product display as of yet.

**Comment by jasperf** [comment]
I checked the JSON response load's validity and found this

```
Error: Parse error on line 1:
<form class = "vari
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

This does seem to be the issue.

**Comment by jasperf** [comment]
Gareth at Plugin Republic will take a look at this compatibility issue as well. Seems to be another PHP error related to the display of the product in question using global add-ons.

**Comment by KittenCodes** [comment]
@jasperf Are you able to save correctly when the Product Extras for WooCommerce plugin is disabled?

**Comment by jasperf** [comment]
@KittenCodes When we do not have the global add-on connected to the product the product saves well. But we need the add-on of course. As for the general error 500 on working and saving the template, do believe only the product with that global add-on has the error. So, this conflict needs to be solved. Gareth has been notified as stated, but he has not come up with a solution yet. I need both Oxygen and WooCommerce Product Add-ons Ultimate so do hope we can work out a solution sooner rather than later.
