### ISSUE TITLE
3.8 RC2 - can't add pages or posts

### ISSUE THREAD

**Issue by larrygroebe** [soflyy/oxygen-bugs-and-features#2229]
website is dev.unityagainstcovid.com/
user: oxygendev
pass: V*wp@6ubOZ@ry8po)OaLh17^

Any attempt at creating new post or page fails with this error:

Error Details
=============
An error of type E_ERROR was caused in line 3843 of the file /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-content/plugins/oxygen/component-framework/components/component.class.php. Error message: Uncaught Error: Call to a member function global_conditions_result() on null in /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-content/plugins/oxygen/component-framework/components/component.class.php:3843
Stack trace:
#0 /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-content/plugins/oxygen/component-framework/components/classes/link-text.class.php(32): CT_Component->validate_shortcode(Array, 'LEARN MORE', 'ct_link_text')
#1 /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-includes/shortcodes.php(343): CT_Link_Text->add_shortcode(Array, 'LEARN MORE', 'ct_link_text')
#2 [internal function]: do_shortcode_tag(Array)
#3 /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-includes/shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(oxy_ri...', 'do_shortcode_ta...', '[oxy_rich_text ...')
#4 /chroot/home/aed54917/2e13a82e94.nxcli.net/html/wp-content/plugins/oxygen/component-framework/components/classes/div-block.class.php(47): do_shortcode('[oxy_rich_text ...')
#5 /chroot/home/aed54917/2e13a82e94.nxcli.n

EDITING pages or posts still work. Just not CREATING them.

SOLUTION: Disabling Oxygen Gutenberg Integration 1.4 fixes the problem!
(but obviously not a true solution)

**Comment by lothisoft** [comment]
Larry,
try this:

in the file /wp-content/plugins/oxygen/component-framework/includes/conditions.php. on line #1165, you will see this code:

	$ajax_action_hooks = array(
		'load_conditions_terms', 
		'load_conditions_tags',
		'load_conditions_categories',
		'ct_get_post_data',
	);


You need to add a new line on #1170, so that the above code changes to:

	$ajax_action_hooks = array(
		'load_conditions_terms', 
		'load_conditions_tags',
		'load_conditions_categories',
		'ct_get_post_data',
                'ct_get_template_data'
	);

That's the solution Oxygen Support provided to me.  It will be part of the final version 3.8.

**Comment by larrygroebe** [comment]
cool, thanks.

**Comment by fifle** [comment]
Adding `'ct_get_template_data'` haven't really helped me to get through that bug.
Any other advice? @Spellhammer ?

**Comment by Spellhammer** [comment]
@fifle Contact us via support so that we can take a look: https://oxygenbuilder.com/support.

**Comment by artovermatter** [comment]
Having this issues as well. @larrygroebe solution of disabling the Gutenberg Integration plugin works. But had to downgrade to 3.7.1 since we require that integration.

**Comment by KittenCodes** [comment]
@artovermatter Please open a support ticket so that we can take a look at this for you.

**Comment by shock2d** [comment]
@KittenCodes That was fixed in 3.8.1
