### ISSUE TITLE
conflict with toolset types and wpgridbuilder

### ISSUE THREAD

**Issue by izuio** [soflyy/oxygen-bugs-and-features#2291]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
with toolset active I cannot add a wpgridbuilder to oxygen without a critical error; but I can add it using a normal wordpress block. 5. I tried on my own environment a few other versions of wpgridbuilder, toolset and oxygen (3.7.1 3.8 and 3.8.1) and I have raised tickets with toolset and wpgridbuilder 

thanks

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qrgfk7wby7s7.oxygen-demo.qsandbox.me/
error is evident here
https://oxygen-qrgfk7wby7s7.oxygen-demo.qsandbox.me/wpgridbuilder/?ct_builder=true&ct_inner=true

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. add apage
2. add a section, columns and a wpgridbuilder grid - the stand blog gris is enough
3. Scroll down to  bottom and see the error - or look in debug log

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

[07-Jul-2021 12:40:00 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/component-init.php on line 610
[07-Jul-2021 12:40:06 UTC] PHP Notice:  Undefined variable: show_gradient in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/toolbar/views/background.view.php on line 167
[07-Jul-2021 12:40:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /sites/ox37.izu.io/files/wp-includes/functions.php on line 4757
[07-Jul-2021 12:40:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /sites/ox37.izu.io/files/wp-includes/functions.php on line 4757
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: html_template in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 297
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: html_template in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 297
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 318
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 319
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: html_template in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 297
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 318
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 319
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined property: OxygenElement::$registeredSelectors in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 350
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: html_template in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 297
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 318
[07-Jul-2021 12:40:22 UTC] PHP Notice:  Undefined index: inlineJS in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 319
[07-Jul-2021 12:40:26 UTC] PHP Notice:  Undefined index: queryOptions in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/single.template.php on line 20
[07-Jul-2021 12:40:26 UTC] PHP Notice:  Undefined index: children in /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 876
[07-Jul-2021 12:40:26 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /sites/ox37.izu.io/files/wp-content/plugins/types/vendor/toolset/toolset-common/inc/toolset.css.component.class.php:261
Stack trace:
#0 /sites/ox37.izu.io/files/wp-content/plugins/types/vendor/toolset/toolset-common/inc/toolset.css.component.class.php(69): Toolset_CssComponent->is_allowed_page()
#1 /sites/ox37.izu.io/files/wp-includes/class-wp-hook.php(292): Toolset_CssComponent->admin_enqueue_scripts()
#2 /sites/ox37.izu.io/files/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /sites/ox37.izu.io/files/wp-includes/plugin.php(484): WP_Hook->do_action()
#4 /sites/ox37.izu.io/files/wp-includes/functions.wp-scripts.php(95): do_action()
#5 /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php(904): wp_print_scripts()
#6 /sites/ox37.izu.io/files/wp-content/plugins/oxygen/component-framework/api/single.template.php(44): OxygenElement->ajax_render_callback()
#7 /sites/ox37.izu.io/files/wp-i in /sites/ox37.izu.io/files/wp-content/plugins/types/vendor/toolset/toolset-common/inc/toolset.css.component.class.php on line 261

**Comment by KittenCodes** [comment]
@izuio There's a fatal error from the Toolset plugin:

PHP Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /sites/ox37.izu.io/files/wp-content/plugins/types/vendor/toolset/toolset-common/inc/toolset.css.component.class.php:261

You would need to report the bug to their team and ask them to investigate.
