### ISSUE TITLE
Woocommerce 6.1.0 Image Gallery doesn't display

### ISSUE THREAD

**Issue by madjedo** [soflyy/oxygen-bugs-and-features#2665]
**Describe the bug**

The latest update of Woocommerce breaks the flex slider / image gallery component when using multiple product images. The whole image gallery component doesn't get displayed.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

Product page with multiple product images:
https://oxygen-qhb5h8z9qdckl.oxygen-demo.qsandbox.me/product/wordpress-pennant/

Product page with single product image:
https://oxygen-qhb5h8z9qdckl.oxygen-demo.qsandbox.me/product/beanie-with-logo/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

1. Install the latest Woocommerce 6.1.0
2. Create a product with multiple images
3. Set up Oxygen product template
4. Visit front-end.

Full changelog of Woocommerce 6.1.0 Final:

https://github.com/woocommerce/woocommerce/blob/release/6.1/changelog.txt

**Comment by KittenCodes** [comment]
Thank you for reporting this to us. Replicated and reported internally.

**Comment by AlkoKod** [comment]
Please solve this ASAP

**Comment by Spellhammer** [comment]
Immediate workaround: Go to Oxygen Settings > Bloat Eliminator and uncheck Disable jQuery Migrate.

We're investigating to see if we can do anything on our end, but this may fall to WooCommerce to fix.

**Comment by madjedo** [comment]
> Immediate workaround: Go to Oxygen Settings > Bloat Eliminator and uncheck Disable jQuery Migrate.
> 
> We're investigating to see if we can do anything on our end, but this may fall to WooCommerce to fix.

Ever considered removing/rewriting all Oxygen JS dependant on jQuery?

**Comment by Spellhammer** [comment]
@madjedo This has nothing to do with Oxygen using or not using jQuery. jQuery migrate is a third-party library that helps with jQuery compatibility issues. It's loaded on WordPress sites by default (included with WP core) and is often unnecessary, so Oxygen allows you to disable it and in-fact disables it by default.

I've contacted WooCommerce support to see if they're going to fix this. If they don't signal that they will, we'll probably stop disabling jQuery migrate by default moving forward to avoid this collision.

**Comment by madjedo** [comment]
@Spellhammer That's putting it mildly... I don't want to make any further comments other then I will wait and see where this goes. But Wordpress already by default disabled jQuery migrate.

**Comment by janvanelst** [comment]
Oxygen Settings > Bloat Eliminator and uncheck Disable jQuery Migrate didn't work for me. The strange thing is that the pictures of my Woocommerce demo data are still displayed, and all images of my own products are gone.

I have this error:
Uncaught TypeError: e.indexOf is not a function
    at S.fn.init.S.fn.load (jquery.min.js:2:84932)
    at new S.fn.init (jquery.min.js:2:25740)
    at S (jquery.min.js:2:1051)
    at Object.setupPaging (jquery.flexslider.min.js:1:4866)
    at Object.setup (jquery.flexslider.min.js:1:4464)
    at Object.init (jquery.flexslider.min.js:1:2106)
    at new v.flexslider (jquery.flexslider.min.js:1:21309)
    at HTMLDivElement.<anonymous> (jquery.flexslider.min.js:1:22487)
    at Function.each (jquery.min.js:2:3003)
    at S.fn.init.each (jquery.min.js:2:1481)
