### ISSUE TITLE
Failing CSS Regeneration when using Reusable Component (simple)

### ISSUE THREAD

**Issue by marceldarvas** [soflyy/oxygen-bugs-and-features#3356]
**Describe the bug**
I was running into AJAX Request Failed during the CSS cache regeneration process which was caused by the following error:

`PHP Fatal error:  Uncaught TypeError: RtCamp\GoogleLogin\Modules\Shortcode::scan_shortcode(): Argument #1 ($output) must be of type string, null given, called in /var/www/example.com/htdocs/wp-includes/class-wp-hook.php on line 310 and defined in /var/www/example.com/htdocs/wp-content/plugins/login-with-google/src/Modules/Shortcode.php:127`

While I initially thought this was caused by the plugin that is mentioned: [Log in with Google](https://wordpress.org/plugins/login-with-google/) I was able to pinpoint the exact cause of this while trying to recreate in sandbox install.
You can find the exact code, that's causing the issue within Oxygen here: https://github.com/rtCamp/login-with-google/blob/0c4ee9c222ff6455b2e8c89d226e15708087401b/src/Modules/Shortcode.php#L127

**Steps required to reproduce the bug:**

1. Install Plugin: [Log in with Google](https://wordpress.org/plugins/login-with-google/) (no need to configure or insert shortcode, as the error occurs even without)
2. Create an Oxygen Template/Page and insert a **Reusable part as a single component**
3. In the Oxygen Settings => CSS Cache: Regeneration Page
4. It will complete but should show an error for the Template/Page that you inserted the Reusable Part into

To overcome this issue, I could swap all reusable parts inserted as Single with the Editable version, and then regeneration was completed without any issues.
Here's the stack trace that I followed to debug:
```
#0 /.../htdocs/wp-includes/class-wp-hook.php(310): RtCamp\GoogleLogin\Modules\Shortcode->scan_shortcode()
#1 /.../htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /.../htdocs/wp-content/plugins/oxygen/component-framework/includes/templates.php(78): apply_filters()
#3 /.../htdocs/wp-content/plugins/oxygen/component-framework/includes/cache.php(163): do_oxygen_elements()
#4 /.../htdocs/wp-content/plugins/oxygen/component-framework/includes/cache-template.php(9): oxygen_vsb_cache_page_css()
#5 /.../htdocs/wp-includes/template-loader.php(106): include('...')
#6 /.../htdocs/wp-blog-header.php(19): require_once('...')
#7 /.../htdocs/index.php(17): require('...')
#8 {main}
```

I will close my issue ticket with them, as I believe this bug is more on the side of Oxygen and not with their plugin: https://github.com/rtCamp/login-with-google/issues/159

**Comment by mymariusz** [comment]
I have the same problem, but also with the ‘Log in with Google’ plug-in disabled.
