### ISSUE TITLE
(3.0 Alpha 2) Fatal error parsing ACF date

### ISSUE THREAD

**Issue by sagararyal** [soflyy/oxygen-bugs-and-features#455]
In a Single CPT Template working with ACF,

`[oxygen data='custom_acf_content' format='M d, Y' settings_path='date']`

should return

example: `Jan 1, 2019`

instead got the error below:
```
Error occurred while rendering shortcode
500

Your server returned a 500 error for the request to [redacted].
Troubleshooting Guide »
```

and on site

```
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (27/09/2019) at position 0 (2): Unexpected character in /app/public/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:580 Stack trace: #0 /app/public/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php(580): DateTime->__construct('27/09/2019') #1 /app/public/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php(359): oxygen_acf_integration->acf_content_handler(Array) #2 /app/public/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php(65): Oxygen_VSB_Dynamic_Shortcodes->oxygen_custom(Array) #3 /app/public/wp-includes/shortcodes.php(325): Oxygen_VSB_Dynamic_Shortcodes->oxygen_vsb_dynamic_shortcode(Array, '', 'oxygen') #4 [internal function]: do_shortcode_tag(Array) #5 /app/public/wp-includes/shortcodes.php(199): preg_replace_callback('/\\[(\\[?)(oxygen...', 'do_shortcode_ta...', '[oxygen ct_sign...') #6 /app/ in /app/public/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php on line 580
The site is experiencing technical difficulties.
```

**Comment by KittenCodes** [comment]
Internal bug report open.

**Comment by srikat** [comment]
It appears like the problem is only when the Return Format of the "Date Picker" type ACF field is the default `d/m/Y`.

In my testing, it is working fine with other Return Formats incl. specifying `d/m/Y` as the custom format.

**Comment by orohellec** [comment]
+1. I had the same issue. The solution provided by Srikat worked for me.

**Comment by KorbinPerry** [comment]
+1 same issue. Other formats seem to work as Srikat mentioned

**Comment by webthread** [comment]
Date and time picker seems to throw a 500 no matter what is specified > https://www.advancedcustomfields.com/resources/date-time-picker/

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.

**Comment by nabonham** [comment]
My situation was very similar, but there was a need to use locale-aware dates (to use short textual representation of the ACF datetime field).

I leave my contribution here. Instead of using (line 564 @ oxygen-acf-integration.php):

`$output = $date->format( $format );`

Change to use the WP native date function (wp_date), since it's locale-aware already.

`$output = wp_date( $format, $date->getTimestamp() );`
