### ISSUE TITLE
Non-US format in ACF field cannot be displayed: fatal error

### ISSUE THREAD

**Issue by davidsingapore** [soflyy/oxygen-bugs-and-features#559]
**Describe the bug**
*A clear and concise description of what the bug is.*
Fatal error when trying to display a single custom post that includes a ACF date field with the format='jS F'.
It seems that days and months are inversed.

Posts are displayed correctly when the days are below the number 12:
07/11/2018
05/12/2018

But fatal error when the days are higher than the number 12:
17/05/2018
14/11/2018

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to 'a custom post created by ACF'
2. Add a date in a date field such as 14/12/2019'
3. Edit template to display the date in the format='jS F' 

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The post should be displayed correctly and show *14th December*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (25/10/2019) at position 0 (2): Unexpected character in /home/wearecar/staging/1/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:580 Stack trace: #0 /home/wearecar/staging/1/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php(580): DateTime->__construct('25/10/2019') #1 /home/wearecar/staging/1/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php(363): oxygen_acf_integration->acf_content_handler(Array) #2 /home/wearecar/staging/1/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php(65): Oxygen_VSB_Dynamic_Shortcodes->oxygen_custom(Array) #3 /home/wearecar/staging/1/wp-includes/shortcodes.php(325): Oxygen_VSB_Dynamic_Shortcodes->oxygen_vsb_dynamic_shortcode(Array, '', 'oxygen') #4 [internal function]: do_shortcode_tag(Array) #5 /home/wearecar/staging/1/wp-includes/shortcodes.php(199): preg_replace_callbac in /home/wearecar/staging/1/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php on line 580

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version 3.0

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
